### ISSUE TITLE
Only Terraform?

### ISSUE THREAD

**Issue by lazzurs** [opentofu/manifesto#58]
Giving this is going to be forking Terraform is this also going to fork the other Hashicorp tools or just Terraform?

I would rather see a foundation take over all of the Hashicorp tooling chain and not just Terraform.

**Comment by EamonKeane** [comment]
Probably only going to happen for Terraform, see e.g.:

https://twitter.com/monadic/status/1691154424708657152

**Comment by SeanKnight** [comment]
Perhaps CNCF would be a good home for the forks.

**Comment by eadderley** [comment]
Given that the earliest signers are companies that make their money off of Terraform in some way or another, I don't think that's likely. It's kind of weird/to be expected because the means by which you could make money off of much of the rest of Hashicorp's stack is already heavily controlled by HC's Enterprise licenses prohibiting that.

**Comment by ZIJ** [comment]
This initiative's scope is only Terraform for now for 2 reasons:

1 - Terraform ecosystem alone is large enough to warrant a dedicated effort

2 - Terraform is differs from Vault and Hashicorp in one fundamental way. It is not a piece of backend that someone could host and charge management fee for (Unlike Vault or Consul or say Elastic or Mongo). It's a language, with a CLI. Much broader ecosystem; much less reasonable move by Hashi. It is sad but understandable for Hashicorp to prevent commercial distribution of Vault for example. To make use of Vault you need a Vault server. Fair enough. But Terraform is different. The server part (Terraform Cloud) which Hashicorp tries to bucket together under Terraform name is not required; and that server part was never open-source in the first place! So unlike with Vault, Hashicorp isn't trying to limit commercial of open-source code. They are trying to force everyone who builds on Terraform the language to only use their closed-source server for running it.

**Comment by bilalq** [comment]
How broad is "ecosystem" defined here. What about CDKTF?

**Comment by jnicholls** [comment]
I want to parrot @bilalq's question. I see CDKTF as intimately a part of TF. I'd love to seek clarification of the following:

1. Does the foundation seek to also maintain a fork of CDKTF?
2. If not, can the foundation shed clarity on whether or not it aims for CDKTF to be compatible with OpenTF in the same way it is compatible with TF? Is the way that CDKTF is layered on top of TF well-enough understood by OpenTF to even make this judgement?

Thanks in advance!

**Comment by chester89** [comment]
I'd like Vault and Consul included as well. But as @eadderley mentioned, that's very unlikely.
I haven't heard of any companies that host them and/or provide operational support, except Hashicorp with their HCP offering

**Comment by JM2K69** [comment]
I think packer need to be fork like terraform.

**Comment by orbang** [comment]
Without CDKTF, terraform is pretty much useless for a lot of companies

**Comment by RyanBijkerk** [comment]
+1
